name: Detect Impacted Folders
description:  Detect Impacted Folders
inputs:
  github-token:
    description: github token.
    required: true
    type: string
  pull_request_id:
    description: id of the pull request.
    required: true
    type: string

runs:
  using: 'node20'
  main:  'index.js'

