name: Detect Impacted Folders
description:  Detect Impacted Folders
inputs:
  github-token:
    description: github token.
    required: true
  pull-request-id:
    description: github token.
    required: true

runs:
  using: 'node20'
  main:  'index.js'

